name: Release with Jitpack

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - refs/tags/*
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build
      run: ./gradlew check
    - name: Release
      run: |
        echo "Triggering JitPack build"

        PACKAGES_URL="https://jitpack.io/com/github/${GITHUB_REPOSITORY}/${GITHUB_REF#refs/tags/}/"
        PACKAGES_FILE="packages.txt"
        touch ${PACKAGES_FILE}
        # Try the URL 6 times before failing
        count=1
        until [[ $count -gt 6 ]] || grep -q build.log ${PACKAGES_FILE} ; do
          echo "Attempt ${count}/6"
        done
